{{- if eq .Values.application.type "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  {{- if not .Values.deployment.hpa.enabled }}
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vaultwarden.selectorLabels" . | nindent 6 }}
  {{- if .Values.deployment.strategy }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 8 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vaultwarden.labels" . | nindent 8 }}
  {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vaultwarden.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.application.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          volumeMounts:
          {{- range $volumeMount := .Values.volumeMounts }}
            - name: {{ $volumeMount.name }}
              mountPath: {{ $volumeMount.mountPath }}
              {{- if $volumeMount.subPath }}
              subPath: {{ $volumeMount.subPath }}
              {{- end }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
            - name: {{ .Values.persistence.name | default "data" }}
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}

          {{- with .Values.env }}
          {{- if gt (len .) 0 }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          
          envFrom:
            {{- if .Values.envFromConfigMaps }}
            {{- range $configMap := .Values.envFromConfigMaps }}
            - configMapRef:
                name: {{ $configMap.name }}
            {{- end }}
            {{- end }}
    
            {{- if .Values.externalSecrets }}
            {{- range $externalSecret := .Values.externalSecrets.secrets }}
            - secretRef:
                name: {{ $externalSecret.name }}
            {{- end }}
            {{- end }}

            {{- if .Values.envFromSecrets }}
            {{- range $secret := .Values.envFromSecrets }}
            - secretRef:
                name: {{ $secret.name }}
            {{- end }}
            {{- end }}

     
      volumes:
         {{- range $volumes := .Values.volumes }}
        - name: {{ $volumes.name }}
          {{- if $volumes.configMap }}
          configMap:
            name: {{ $volumes.configMap.name }}
            {{- if $volumes.configMap.items }}
            items:
              {{- toYaml $volumes.configMap.items | nindent 16 }}
            {{- end }}
          {{- end }}
          {{- if $volumes.secret }}
          secret:
            secretName: {{ $volumes.secret.secretName }}
            {{- if $volumes.secret.items }}
            items:
              {{- toYaml $volumes.secret.items | nindent 16 }}
            {{- end }}
          {{- end }}
        {{- end }}

        {{- if .Values.persistence.enabled }}
        - name: {{ .Values.persistence.name | default "data" }}
          persistentVolumeClaim:
            claimName: {{ include "vaultwarden.fullname" . }}-data
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}