{{- $labels := include "vaultwarden.labels" . -}}
{{- if .Values.externalSecrets }}
{{- range $externalSecret := .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
  labels:
    {{ $labels | nindent 4 }}
spec:
  refreshInterval: {{ $externalSecret.refreshInterval | default "1h" }}
  secretStoreRef: 
    name: {{ $externalSecret.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ $externalSecret.name }}
  dataFrom:
  - extract:
      key: {{ $externalSecret.path }}
{{- end }}
{{- end }}